DROP TABLE STOCK; 
DROP TABLE ALMACEN; 
DROP TABLE DETALLE;
DROP TABLE PRODUCTO;
DROP TABLE SUBCAT;
DROP TABLE CATEGORIA; 
DROP TABLE MARCA;
DROP TABLE PEDIDO;
DROP TABLE VENDEDOR; 
DROP TABLE USUARIO;

CREATE TABLE USUARIO
(
  UCOD NUMBER(10), 
  NOMBRE VARCHAR2(100),
  CORREO VARCHAR2(100),
  CONTRASEÑA VARCHAR2(50),
  PRIMARY KEY (UCOD)
);

INSERT INTO USUARIO VALUES ('1000' , 'VELASQUEZ SUYBATE, EMANUEL' , 'emanuvesuy@gmail.com' , 'Prueba123');
INSERT INTO USUARIO VALUES ('1001' , 'MIYAHIRA ARAKAKI, ALBERTO' , 'albermiara@gmail.com' , 'Prueba123');
INSERT INTO USUARIO VALUES ('1002' , 'BRAGAGNINI ZAMORA DE WOODS, LUZ MARIA' , 'luzmbrzam@gmail.com' , 'Prueba123');
COMMIT;

CREATE TABLE VENDEDOR
(
    VCOD NUMBER(10),
    VNAME VARCHAR2(50),
    PRIMARY KEY(VCOD)
);


CREATE TABLE PEDIDO
(
  PCOD NUMBER(10),
  DIRECCION VARCHAR2(100),
  METODO VARCHAR2(20),
  MONTO NUMBER(10),
  UCOD NUMBER(10),
  VCOD NUMBER(10),
  FECHA_P DATE, 
  PRIMARY KEY (PCOD),
  FOREIGN KEY (UCOD) REFERENCES USUARIO(UCOD),
  FOREIGN KEY (VCOD) REFERENCES VENDEDOR(VCOD)
);

CREATE TABLE MARCA
(
  MNAME VARCHAR2(50),
  WEB VARCHAR2(50),
  PRIMARY KEY (MNAME)
);

INSERT INTO MARCA VALUES('WINTERS' , 'https://winters.com/' );
INSERT INTO MARCA VALUES('PICARAS' , NULL);
INSERT INTO MARCA VALUES('NOEL' , 'https://noel.com.co/');
INSERT INTO MARCA VALUES('KRYZPO' , NULL);
INSERT INTO MARCA VALUES('OLÉ OLÉ' , NULL);
INSERT INTO MARCA VALUES('MONTERREY' , NULL);
INSERT INTO MARCA VALUES('CHOCOLISTO' , 'https://www.chocolisto.com/');
COMMIT;

CREATE TABLE CATEGORIA
(
  CNAME VARCHAR2(50),
  PRIMARY KEY (CNAME)
);

INSERT INTO CATEGORIA VALUES('GOLOSINAS');
INSERT INTO CATEGORIA VALUES('PANETONES');
INSERT INTO CATEGORIA VALUES('REPOSTERIA');
INSERT INTO CATEGORIA VALUES('BEBIDAS');
INSERT INTO CATEGORIA VALUES('GALLETAS');
INSERT INTO CATEGORIA VALUES('PATATAS FRITAS');
INSERT INTO CATEGORIA VALUES('CHOCOLATE EN POLVO');
INSERT INTO CATEGORIA VALUES('MARSHMALLOWS');
COMMIT;

CREATE TABLE SUBCAT
(
  CNAME VARCHAR2(50),
  SUBC VARCHAR2(50),
  PRIMARY KEY (SUBC),
  FOREIGN KEY (CNAME) REFERENCES CATEGORIA
);

INSERT INTO SUBCAT VALUES('GOLOSINAS' , 'CHOCOLATE');
INSERT INTO SUBCAT VALUES('REPOSTERIA' , 'COBERTURA');
INSERT INTO SUBCAT VALUES('BEBIDAS' , 'COCOA');
INSERT INTO SUBCAT VALUES('GALLETAS' , 'DULCE');
INSERT INTO SUBCAT VALUES('REPOSTERIA' , 'GRAJEAS');
INSERT INTO SUBCAT VALUES('REPOSTERIA' , 'CHISPAS');
INSERT INTO SUBCAT VALUES('BEBIDAS' , 'CAFE');
COMMIT; 


CREATE TABLE PRODUCTO
(
  PRECIO NUMBER(10),
  SKU NUMBER(10),
  NOMBRE VARCHAR2(50),
  PESO NUMBER(20),
  MNAME VARCHAR2(50),
  SUBC VARCHAR2(50),
  PRIMARY KEY (SKU),
  FOREIGN KEY (MNAME) REFERENCES MARCA(MNAME),
  FOREIGN KEY (SUBC) REFERENCES SUBCAT(SUBC)
);

CREATE TABLE DETALLE 
(
  MONTO NUMBER(10),
  DETID NUMBER(10),
  CANT NUMBER(10),
  PCOD NUMBER(10),
  SKU NUMBER(10),
  PRIMARY KEY (DETID),
  FOREIGN KEY (PCOD) REFERENCES PEDIDO(PCOD),
  FOREIGN KEY (SKU) REFERENCES PRODUCTO(SKU)
);


CREATE TABLE ALMACEN
(
    ANAME VARCHAR2(50),
    DIRECCION VARCHAR2(100),
    PRIMARY KEY (ANAME)
);


CREATE TABLE STOCK
(
    ANAME VARCHAR2(50),
    SKU NUMBER(10),
    STOCK NUMBER(10),
    FOREIGN KEY (ANAME) REFERENCES ALMACEN,
    FOREIGN KEY (SKU) REFERENCES PRODUCTO
);


