/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PI_library;

import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

/**
 *
 * @author javier
 */
public class MoveStocks extends javax.swing.JPanel {

    Connect conn;
    Connection reg;
    
    /**
     * Creates new form MoveStocks
     */
    public MoveStocks(Connect conn) throws SQLException {
        initComponents();
        this.conn = conn;
        reg = this.conn.getConnection();
        getAlmacen();
        getProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        Title1 = new javax.swing.JLabel();
        box_products = new javax.swing.JComboBox<>();
        box_destino = new javax.swing.JComboBox<>();
        box_origen = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        cantidad_mover = new javax.swing.JTextField();
        Text5 = new javax.swing.JLabel();
        cantidad_destino = new javax.swing.JLabel();
        Text7 = new javax.swing.JLabel();
        btn_mover = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text8 = new javax.swing.JLabel();
        Text9 = new javax.swing.JLabel();
        cantidad_origen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(750, 430));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 10, 350));

        Title1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title1.setText("Mover stock de un producto entre almacenes ");
        add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        box_products.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        box_products.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_productsActionPerformed(evt);
            }
        });
        add(box_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 280, -1));

        box_destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        box_destino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_destino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        box_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_destinoActionPerformed(evt);
            }
        });
        add(box_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 280, -1));

        box_origen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        box_origen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_origen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        box_origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_origenActionPerformed(evt);
            }
        });
        add(box_origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 280, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 260, -1));

        cantidad_mover.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cantidad_mover.setForeground(new java.awt.Color(102, 102, 102));
        cantidad_mover.setText("Cantidad");
        cantidad_mover.setBorder(null);
        cantidad_mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cantidad_moverMousePressed(evt);
            }
        });
        cantidad_mover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad_moverActionPerformed(evt);
            }
        });
        add(cantidad_mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 260, 30));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Cantidad de stock a mover");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        cantidad_destino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantidad_destino.setText("Cant: ");
        add(cantidad_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Almacén origen ");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        btn_mover.setBackground(new java.awt.Color(18, 90, 173));
        btn_mover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_moverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_moverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_moverMousePressed(evt);
            }
        });
        btn_mover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subir");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        btn_mover.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 30));

        add(btn_mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 260, 50));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Almacén destino ");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Producto");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        cantidad_origen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantidad_origen.setText("Cant: ");
        add(cantidad_origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cantidad_moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidad_moverMousePressed
        // TODO add your handling code here:
        if(cantidad_mover.getText().equals("Cantidad")){
            cantidad_mover.setText("");
        }
    }//GEN-LAST:event_cantidad_moverMousePressed

    private void cantidad_moverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad_moverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad_moverActionPerformed

    private void btn_moverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_moverMouseEntered
        setColor(btn_mover);
    }//GEN-LAST:event_btn_moverMouseEntered

    private void btn_moverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_moverMouseExited
        resetColor(btn_mover);
    }//GEN-LAST:event_btn_moverMouseExited

    private void btn_moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_moverMousePressed
       
        try {
            move();
            updtCant();
        } catch (SQLException ex) {
            Logger.getLogger(MoveStocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_moverMousePressed

    private void box_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_productsActionPerformed
        try {
            // TODO add your handling code here:
            updtCant();
        } catch (SQLException ex) {
            Logger.getLogger(MoveStocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_box_productsActionPerformed

    private void box_origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_origenActionPerformed
        try {
            updtCant();
        } catch (SQLException ex) {
            Logger.getLogger(MoveStocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_box_origenActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        try {
            // TODO add your handling code here:
            move();
        } catch (SQLException ex) {
            Logger.getLogger(MoveStocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MousePressed

    private void box_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_destinoActionPerformed
        try {
            // TODO add your handling code here:
            updtCant();
        } catch (SQLException ex) {
            Logger.getLogger(MoveStocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_box_destinoActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(cantidad_mover.getText().equals("")){
            cantidad_mover.setText("Cantidad");
        }
    }//GEN-LAST:event_formMouseClicked
    public void getAlmacen() throws SQLException{
        Statement st = reg.createStatement();
        String sql = "SELECT * FROM ALMACEN";
        ResultSet rs = st.executeQuery(sql);
        DefaultComboBoxModel boxModel = new DefaultComboBoxModel(new String [] {"-----ALMACEN ORIGEN------"});
        while(rs.next()){
            boxModel.addElement(rs.getString("ANAME"));
        }
        box_origen.setModel(boxModel);
        
        rs = st.executeQuery(sql);
        DefaultComboBoxModel boxModel1 = new DefaultComboBoxModel(new String [] {"-----ALMACEN DESTINO------"});
        while(rs.next()){
            boxModel1.addElement(rs.getString("ANAME"));
        }
        box_destino.setModel(boxModel1);
    }
    
    public String getSku(String pname) throws SQLException{
        Statement st = reg.createStatement();
        String sql = "SELECT * FROM PRODUCTO";
        ResultSet rs = st.executeQuery(sql);
        while(rs.next()){
            String name, sku;
            name = rs.getString("NOMBRE");
            sku = rs.getString("SKU");
            if(pname.equals(name)){
                return sku;
            }
        }
        return "-1";
    }
    
    public void getProduct() throws SQLException{
        
        Statement st = reg.createStatement();
        String sql = "SELECT * FROM PRODUCTO";
        ResultSet rs = st.executeQuery(sql);
        DefaultComboBoxModel boxModel = new DefaultComboBoxModel(new String [] {"-----Producto------"});
        while(rs.next()){
            boxModel.addElement(rs.getString("NOMBRE"));
        }
        box_products.setModel(boxModel);
        
    }
    
    public void move() throws SQLException{
        if(box_products.getSelectedItem().equals("-----Producto------") ||
                box_origen.getSelectedItem().equals("-----ALMACEN ORIGEN------") ||
                box_destino.getSelectedItem().equals("-----ALMACEN DESTINO------") ||
                cantidad_mover.getText().equals("Cantidad")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Se debe llenar el formulario \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            CallableStatement cstm = reg.prepareCall("{call moveStocks(? , ? , ? , ?)}");
            cstm.setString(1, String.valueOf(box_origen.getSelectedItem()) );
            cstm.setInt(2, Integer.parseInt(getSku(String.valueOf(box_products.getSelectedItem()))));
            cstm.setString(3, String.valueOf(box_destino.getSelectedItem()));
            cstm.setInt(4, Integer.parseInt(cantidad_mover.getText()));
            cstm.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Se ha movido el stock con éxito \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
        }
    }
    public void updtCant() throws SQLException{
        if(!box_products.getSelectedItem().equals("-----Producto------")){
            if(!box_origen.getSelectedItem().equals("-----ALMACEN ORIGEN------")){
                CallableStatement cstm = reg.prepareCall("{? = call getStocks(? , ?)}");
                cstm.registerOutParameter(1, Types.INTEGER);
                cstm.setString(2, String.valueOf(box_origen.getSelectedItem()));
                cstm.setInt(3, Integer.parseInt(getSku(String.valueOf(box_products.getSelectedItem()))));
                cstm.executeUpdate();
                int stock = cstm.getInt(1);
                cantidad_origen.setText("Cant: " + stock);
            }
            if(!box_destino.getSelectedItem().equals("-----ALMACEN DESTINO------")){
                CallableStatement cstm = reg.prepareCall("{? = call getStocks(? , ?)}");
                cstm.registerOutParameter(1, Types.INTEGER);
                cstm.setString(2, String.valueOf(box_destino.getSelectedItem()));
                cstm.setInt(3, Integer.parseInt(getSku(String.valueOf(box_products.getSelectedItem()))));
                cstm.executeUpdate();
                int stock = cstm.getInt(1);
                cantidad_destino.setText("Cant: " + stock);
            }
        }
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title1;
    private javax.swing.JComboBox<String> box_destino;
    private javax.swing.JComboBox<String> box_origen;
    private javax.swing.JComboBox<String> box_products;
    private javax.swing.JPanel btn_mover;
    private javax.swing.JLabel cantidad_destino;
    private javax.swing.JTextField cantidad_mover;
    private javax.swing.JLabel cantidad_origen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
