/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PI_library;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import static PI_library.Dashboard.content;
import java.awt.BorderLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Antonio
 */
public class Pedidos extends javax.swing.JPanel {

    Connect conn;
    Connection reg;
    /**
     * Creates new form Principal
     */
    public Pedidos() {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        try {
            getPedidos();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        body = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        cliente_name = new javax.swing.JTextField();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        ver_detalle = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Title1 = new javax.swing.JLabel();
        monto_final = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 620, 10));

        cliente_name.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cliente_name.setForeground(new java.awt.Color(102, 102, 102));
        cliente_name.setText("Ingrese el nombre del cliente");
        cliente_name.setBorder(null);
        cliente_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cliente_nameMousePressed(evt);
            }
        });
        add(cliente_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 620, 30));

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 80, 30));

        edit.setBackground(new java.awt.Color(18, 90, 173));
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editMousePressed(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 395, 80, -1));

        ver_detalle.setBackground(new java.awt.Color(18, 90, 173));
        ver_detalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ver_detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ver_detalleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ver_detalleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ver_detalleMousePressed(evt);
            }
        });
        ver_detalle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ver detalle");
        ver_detalle.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        add(ver_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 130, 40));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "COD PEDIDO", "CLIENTE", "DIRECCION", "FECHA", "VENDEDOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 720, 270));

        Title1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title1.setText("Pedidos");
        add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        monto_final.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add(monto_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 230, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void cliente_nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliente_nameMousePressed
       if(cliente_name.getText().equals("Ingrese el nombre del cliente"))
        cliente_name.setText("");
    }//GEN-LAST:event_cliente_nameMousePressed

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        setColor(button);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColor(button);
    }//GEN-LAST:event_buttonMouseExited

    private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_editMouseEntered

    private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_editMouseExited

    private void ver_detalleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ver_detalleMouseEntered
        setColor(ver_detalle);
    }//GEN-LAST:event_ver_detalleMouseEntered

    private void ver_detalleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ver_detalleMouseExited
        resetColor(ver_detalle);
    }//GEN-LAST:event_ver_detalleMouseExited

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if(cliente_name.getText().equals("") || cliente_name.getText() == null || cliente_name.getText().equals(" "))
            cliente_name.setText("Ingrese el nombre del cliente");
    }//GEN-LAST:event_jTable1MousePressed
    // BORRAR
    private void ver_detalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ver_detalleMousePressed

        try {
            searchDetalles();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ver_detalleMousePressed

    // EDITAR
    private void editMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMousePressed
       
    }//GEN-LAST:event_editMousePressed
    // BUSCAR
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
       
    }//GEN-LAST:event_buttonMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        if(cliente_name.getText().equals("") || cliente_name.getText().equals("Ingrese el nombre del cliente") 
                || cliente_name.getText().equals(" ")){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar el campo de nombre. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                searchByName();
            } catch (SQLException ex) {
                Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel1MousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    private void getPedidos() throws SQLException{
        Statement stm = reg.createStatement();
        String sql = "SELECT P.PCOD CODIGO, U.NOMBRE NAME, P.DIRECCION , P.FECHA_P FECHA , V.VNAME "
                + "FROM PEDIDO P , USUARIO U, VENDEDOR  V "
                + "WHERE P.UCOD = U.UCOD AND P.VCOD = V.VCOD";
        ResultSet rs = stm.executeQuery(sql);
        String col[] = {"Cod. Pedido" , "Cliente" , "Direccion" , "Fecha" , "Vendedor"};
        DefaultTableModel tableModel = new DefaultTableModel(col,0);
        while(rs.next()){
            String pcod = rs.getString("CODIGO");
            String name = rs.getString("NAME");
            String direccion = rs.getString("DIRECCION");
            String fecha = rs.getString("FECHA").substring(0,10);
            String vname = rs.getString("VNAME");
            String row[] = {pcod, name, direccion, fecha , vname};
            tableModel.addRow(row);
        }
        jTable1.setModel(tableModel);
    }
    
    private void searchByName() throws SQLException{
        Statement stm = reg.createStatement();
        String fin = cliente_name.getText().toUpperCase();
        String sql = "SELECT P.PCOD CODIGO, U.NOMBRE NAME, P.DIRECCION , P.FECHA_P FECHA , V.VNAME "
                + "FROM PEDIDO P , USUARIO U, VENDEDOR  V "
                + "WHERE P.UCOD = U.UCOD AND P.VCOD = V.VCOD"
                + " AND (U.NOMBRE) LIKE '%" + fin + "%'";
        ResultSet rs = stm.executeQuery(sql);
        String col[] = {"Cod. Pedido" , "Cliente" , "Direccion" , "Fecha" , "Vendedor"};
        DefaultTableModel tableModel = new DefaultTableModel(col,0);
        while(rs.next()){
            String pcod = rs.getString("CODIGO");
            String name = rs.getString("NAME");
            String direccion = rs.getString("DIRECCION");
            String fecha = rs.getString("FECHA").substring(0,10);
            String vname = rs.getString("VNAME");
            String row[] = {pcod, name, direccion, fecha , vname};
            tableModel.addRow(row);
        }
        jTable1.setModel(tableModel);
    }
    
    private void searchDetalles() throws SQLException{
        int row = jTable1.getSelectedRow();
        if(row == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un pedido \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            Statement st = reg.createStatement();
            int sku = Integer.valueOf(jTable1.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT MNAME , SUBC , NOMBRE , VENTA_U , PRECIO , MONTO "
                    + "FROM PRODUCTO P , DETALLE D "
                    + "WHERE D.PCOD = " + sku +" "
                    + "AND D.SKU = P.SKU";
            ResultSet rs = st.executeQuery(sql);
            String col[] = {"MARCA" , "SUBCATEGORIA" , "NOM. PROD" , "V. UNIT" , "PRECIO U." , "MONTO"};
            DefaultTableModel tableModel = new DefaultTableModel(col , 0);
            while(rs.next()){
                String marca = rs.getString("MNAME");
                String subcat = rs.getString("SUBC");
                String nombre = rs.getString("NOMBRE");
                String venta_u = rs.getString("VENTA_U");
                String precio = rs.getString("PRECIO");
                String monto = rs.getString("MONTO");
                String fila[] = {marca, subcat, nombre, venta_u , precio, monto};
                tableModel.addRow(fila);
            }
            jTable1.setModel(tableModel);
            sql = "SELECT SUM(MONTO) suma FROM PRODUCTO P , DETALLE D WHERE D.PCOD = " + sku + " AND D.SKU = P.SKU";
            rs = st.executeQuery(sql);
            String montoTotal = null;
            while(rs.next()){
                montoTotal = rs.getString("suma");
            }
            monto_final.setText("MONTO FINAL: " + montoTotal);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title1;
    private javax.swing.JPanel body;
    private javax.swing.JPanel button;
    private javax.swing.JTextField cliente_name;
    private javax.swing.JPanel edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel monto_final;
    private javax.swing.JPanel ver_detalle;
    // End of variables declaration//GEN-END:variables
}
