/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PI_library;

import static PI_library.Dashboard.content;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javier
 */
public class Prod extends javax.swing.JPanel {

    /**
     * Creates new form Prod
     */
    
    Connect conn;
    Connection reg;
    
    
    public Prod() {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        try{
            getProducts();
        }catch (SQLException ex) {
            Logger.getLogger(Prod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_updt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_add = new javax.swing.JPanel();
        lbl_add = new javax.swing.JLabel();
        btn_delete = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SKU", "Nombre", "PRECIO", "PESO", "MNAME", "SUBCATEGORIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 710, 260));

        btn_updt.setBackground(new java.awt.Color(18, 90, 173));
        btn_updt.setForeground(new java.awt.Color(18, 90, 173));
        btn_updt.setToolTipText("");
        btn_updt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_updtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_updtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_updtMousePressed(evt);
            }
        });
        btn_updt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actualizar ");
        jLabel2.setToolTipText("");
        jLabel2.setVerifyInputWhenFocusTarget(false);
        btn_updt.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 40));

        add(btn_updt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 130, 40));

        btn_add.setBackground(new java.awt.Color(18, 90, 173));
        btn_add.setForeground(new java.awt.Color(18, 90, 173));
        btn_add.setToolTipText("");
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addMousePressed(evt);
            }
        });
        btn_add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_add.setForeground(new java.awt.Color(255, 255, 255));
        lbl_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_add.setText("Añadir");
        lbl_add.setToolTipText("");
        lbl_add.setVerifyInputWhenFocusTarget(false);
        lbl_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_addMousePressed(evt);
            }
        });
        btn_add.add(lbl_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 90, 40));

        add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 130, 40));

        btn_delete.setBackground(new java.awt.Color(18, 90, 173));
        btn_delete.setForeground(new java.awt.Color(18, 90, 173));
        btn_delete.setToolTipText("");
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_deleteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_deleteMousePressed(evt);
            }
        });
        btn_delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar");
        jLabel1.setToolTipText("");
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        btn_delete.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 40));

        add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 130, 40));

        Title1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title1.setText("PRODUCTOS");
        add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseEntered
        setColor(btn_add);
    }//GEN-LAST:event_btn_addMouseEntered

    private void btn_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseExited
        resetColor(btn_add);
    }//GEN-LAST:event_btn_addMouseExited

    private void btn_addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMousePressed
        UpProd p1 = null;
        try {
            p1 = new UpProd();
        } catch (SQLException ex) {
            Logger.getLogger(Prod.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_addMousePressed

    private void lbl_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMouseEntered
        setColor(btn_add);
    }//GEN-LAST:event_lbl_addMouseEntered

    private void lbl_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMouseExited
        resetColor(btn_add);
    }//GEN-LAST:event_lbl_addMouseExited

    private void lbl_addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMousePressed
        UpProd p1 = null;
        try {
            p1 = new UpProd();
        } catch (SQLException ex) {
            Logger.getLogger(Prod.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_lbl_addMousePressed

    private void btn_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseEntered
        setColor(btn_delete);
    }//GEN-LAST:event_btn_deleteMouseEntered

    private void btn_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseExited
        resetColor(btn_delete);
    }//GEN-LAST:event_btn_deleteMouseExited

    private void btn_deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMousePressed
        try{
            eliminarProducto();
            getProducts();
        }catch (SQLException ex) {
            Logger.getLogger(Prod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_deleteMousePressed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        setColor(btn_delete);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        resetColor(btn_delete);
    }//GEN-LAST:event_jLabel1MouseExited

    private void btn_updtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updtMouseEntered
        setColor(btn_updt);
    }//GEN-LAST:event_btn_updtMouseEntered

    private void btn_updtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updtMouseExited
        resetColor(btn_updt);
    }//GEN-LAST:event_btn_updtMouseExited

    private void btn_updtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updtMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        try{
            eliminarProducto();
            getProducts();
        }catch (SQLException ex) {
            Logger.getLogger(Prod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MousePressed

    
    //----------------------FUNCIONES----------------------------
    
    private void getProducts() throws SQLException{
        Statement stm = reg.createStatement();
        String sql = "SELECT * FROM PRODUCTO ORDER BY SKU";
        ResultSet rs = stm.executeQuery(sql);
        String col[] = {"SKU" , "PRECIO" , "NOMBRE" , "PESO" , "MARCA" , "SUBCATEGORIA"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        while(rs.next()){
            String sku = rs.getString("SKU");
            String precio = rs.getString("PRECIO");
            String name = rs.getString("NOMBRE");
            String peso = rs.getString("PESO");
            String mnam = rs.getString("MNAME");
            String subc = rs.getString("SUBC");
            String row[] = {sku , precio, name, peso, mnam , subc};
            tableModel.addRow(row);
        }
        jTable1.setModel(tableModel);
    }
    
    private void eliminarProducto() throws SQLException{
        try{
            int row = jTable1.getSelectedRow();
            if(row >= 0){
                Statement stm = reg.createStatement();
                String sku = String.valueOf(jTable1.getModel().getValueAt(row, 0));
                String sql = "DELETE FROM PRODUCTO WHERE SKU = " + sku; 
                stm.executeUpdate(sql);
                javax.swing.JOptionPane.showMessageDialog(this, "Se ha borrado correctamente el producto. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el producto a borrar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }catch (HeadlessException | SQLException ex) {
            Logger.getLogger(Prod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    // ------- FUNCIONES PARA ESTABLECER COLORES A LOS BOTONES ------ 
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title1;
    private javax.swing.JPanel btn_add;
    private javax.swing.JPanel btn_delete;
    private javax.swing.JPanel btn_updt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_add;
    // End of variables declaration//GEN-END:variables
}
