/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PI_library;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

import static PI_library.Dashboard.content;
import java.awt.BorderLayout;
import oracle.net.aso.n;

/**
 *
 * @author Antonio
 */
public class Stocks extends javax.swing.JPanel {

    Connect conn;
    Connection reg;
    /**
     * Creates new form Principal
     */
    public Stocks() {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        try {
            GetReports();
        } catch (SQLException ex) {
            Logger.getLogger(Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        aniadirStock = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        nom_prod = new javax.swing.JTextField();
        button1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        nom_almacen = new javax.swing.JTextField();
        btn_delete = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        button13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        button14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        button15 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        button16 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        button17 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        button18 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        button19 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        button20 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Reporte de stock");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SKU", "NOMBRE", "ALMACEN", "STOCKS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTable1InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 750, 280));

        aniadirStock.setBackground(new java.awt.Color(18, 90, 173));
        aniadirStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aniadirStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aniadirStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aniadirStockMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aniadirStockMousePressed(evt);
            }
        });
        aniadirStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Añadir");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        aniadirStock.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        add(aniadirStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 140, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 260, 10));

        nom_prod.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nom_prod.setForeground(new java.awt.Color(102, 102, 102));
        nom_prod.setText("Ingrese el nombre del producto");
        nom_prod.setBorder(null);
        nom_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nom_prodMousePressed(evt);
            }
        });
        nom_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_prodActionPerformed(evt);
            }
        });
        add(nom_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 270, 30));

        button1.setBackground(new java.awt.Color(18, 90, 173));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
        });
        button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Buscar");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        button1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, -1));

        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 80, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator3.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 260, 10));

        nom_almacen.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nom_almacen.setForeground(new java.awt.Color(102, 102, 102));
        nom_almacen.setText("Ingrese el nombre del almacen");
        nom_almacen.setBorder(null);
        nom_almacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nom_almacenMousePressed(evt);
            }
        });
        nom_almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_almacenActionPerformed(evt);
            }
        });
        add(nom_almacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 270, 30));

        btn_delete.setBackground(new java.awt.Color(18, 90, 173));
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_deleteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_deleteMousePressed(evt);
            }
        });
        btn_delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Eliminar");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        btn_delete.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        button13.setBackground(new java.awt.Color(18, 90, 173));
        button13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button13MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button13MousePressed(evt);
            }
        });
        button13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Editar");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        button13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button14.setBackground(new java.awt.Color(18, 90, 173));
        button14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button14MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button14MousePressed(evt);
            }
        });
        button14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Actualizar");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        button14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button13.add(button14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        button15.setBackground(new java.awt.Color(18, 90, 173));
        button15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button15MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button15MousePressed(evt);
            }
        });
        button15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Actualizar");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });
        button15.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button16.setBackground(new java.awt.Color(18, 90, 173));
        button16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button16MousePressed(evt);
            }
        });
        button16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Actualizar");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
        });
        button16.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button15.add(button16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        button13.add(button15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 140, 30));

        button17.setBackground(new java.awt.Color(18, 90, 173));
        button17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button17MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button17MousePressed(evt);
            }
        });
        button17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Editar");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
        });
        button17.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button18.setBackground(new java.awt.Color(18, 90, 173));
        button18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button18MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button18MousePressed(evt);
            }
        });
        button18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Actualizar");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel19MousePressed(evt);
            }
        });
        button18.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button17.add(button18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        button19.setBackground(new java.awt.Color(18, 90, 173));
        button19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button19MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button19MousePressed(evt);
            }
        });
        button19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Actualizar");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel20MousePressed(evt);
            }
        });
        button19.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button20.setBackground(new java.awt.Color(18, 90, 173));
        button20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button20MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button20MousePressed(evt);
            }
        });
        button20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Actualizar");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
        });
        button20.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button19.add(button20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        button17.add(button19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 140, 30));

        button13.add(button17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 140, 30));

        add(button13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1InputMethodTextChanged
        //nothing
    }//GEN-LAST:event_jTable1InputMethodTextChanged

    private void aniadirStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aniadirStockMouseEntered
        setColor(aniadirStock);
    }//GEN-LAST:event_aniadirStockMouseEntered

    private void aniadirStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aniadirStockMouseExited
        resetColor(aniadirStock);
    }//GEN-LAST:event_aniadirStockMouseExited

    private void aniadirStockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aniadirStockMousePressed

        UpStocks p1 = new UpStocks();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_aniadirStockMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        UpStocks p1 = new UpStocks();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jLabel1MousePressed

    private void nom_prodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nom_prodMousePressed
        if(nom_prod.getText().equals("Ingrese el nombre del producto"))
            nom_prod.setText("");
        if(nom_almacen.getText().equals("") || nom_almacen.getText() == null)
            nom_almacen.setText("Ingrese el nombre del almacen");
    }//GEN-LAST:event_nom_prodMousePressed

    private void button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseEntered
        setColor(button1);
    }//GEN-LAST:event_button1MouseEntered

    private void button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseExited
        resetColor(button1);
    }//GEN-LAST:event_button1MouseExited

    private void button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MousePressed
        try {
            buscar();
        } catch (SQLException ex) {
            Logger.getLogger(Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button1MousePressed

    private void nom_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_prodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_prodActionPerformed

    private void nom_almacenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nom_almacenMousePressed
        if(nom_almacen.getText().equals("Ingrese el nombre del almacen"))
            nom_almacen.setText("");
        if(nom_prod.getText().equals("") || nom_prod.getText() == null)
            nom_prod.setText("Ingrese el nombre del producto");
    }//GEN-LAST:event_nom_almacenMousePressed

    private void nom_almacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_almacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_almacenActionPerformed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
       try {
            deleteStock();
            GetReports();
        } catch (SQLException ex) {
            Logger.getLogger(Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel6MousePressed

    private void btn_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseEntered
        setColor(btn_delete);
    }//GEN-LAST:event_btn_deleteMouseEntered

    private void btn_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseExited
        resetColor(btn_delete);
    }//GEN-LAST:event_btn_deleteMouseExited

    private void btn_deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMousePressed
        try {
            deleteStock();
            GetReports();
        } catch (SQLException ex) {
            Logger.getLogger(Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_deleteMousePressed

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        try{
            passToUpStocks();
        }catch (SQLException ex) {
            Logger.getLogger(Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel14MousePressed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MousePressed

    private void button14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button14MouseEntered

    private void button14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button14MouseExited

    private void button14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button14MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button14MousePressed

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MousePressed

    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MousePressed

    private void button16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button16MouseEntered

    private void button16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button16MouseExited

    private void button16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button16MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button16MousePressed

    private void button15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button15MouseEntered

    private void button15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button15MouseExited

    private void button15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button15MousePressed

    private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MousePressed

    private void jLabel19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MousePressed

    private void button18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button18MouseEntered

    private void button18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button18MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button18MouseExited

    private void button18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button18MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button18MousePressed

    private void jLabel20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MousePressed

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MousePressed

    private void button20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button20MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button20MouseEntered

    private void button20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button20MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button20MouseExited

    private void button20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button20MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button20MousePressed

    private void button19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button19MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button19MouseEntered

    private void button19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button19MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button19MouseExited

    private void button19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button19MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button19MousePressed

    private void button17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button17MouseEntered

    private void button17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button17MouseExited

    private void button17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button17MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button17MousePressed

    private void button13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button13MouseEntered

    private void button13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button13MouseExited

    private void button13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button13MousePressed
        //editar 
        try{
            passToUpStocks();
        }catch (SQLException ex) {
            Logger.getLogger(Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button13MousePressed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        setColor(btn_delete);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        resetColor(btn_delete);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        setColor(button1);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        resetColor(button1);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        try {
            buscar();
        } catch (SQLException ex) {
            Logger.getLogger(Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    public void passToUpStocks() throws SQLException{
        try{
            int pos = jTable1.getSelectedRow();
            if(pos <= -1){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un stock. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            Statement st = reg.createStatement();
            String sql = "SELECT * FROM STOCK , PRODUCTO , ALMACEN   "
                + "WHERE ALMACEN.ANAME = STOCK.ANAME AND "
                + "STOCK.SKU = PRODUCTO.SKU ORDER BY PRODUCTO.SKU";
            ResultSet counter = st.executeQuery(sql);
            int cont = 0;
            while(counter.next()) cont++;
            String[][] list = new String[cont][4];
            int i = 0;
            
            ResultSet re = st.executeQuery(sql);
            while(re.next()){
                list[i][0] = re.getString("SKU");
                list[i][1] = re.getString("NOMBRE");
                list[i][2] = re.getNString("ANAME");
                list[i][3] = re.getString("STOCK");
                i++;
            }
            UpStocks p2 = new UpStocks(list[pos][2] ,list[pos][1] , list[pos][3] , list[pos][0]);
            p2.setSize(750, 430);
            p2.setLocation(0, 0);

            content.removeAll();
            content.add(p2, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
            
        }catch (SQLException ex) {
            Logger.getLogger(Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void GetReports() throws SQLException{
        Statement stm = reg.createStatement();
        String sql = "SELECT * FROM STOCK , PRODUCTO , ALMACEN   "
                + "WHERE ALMACEN.ANAME = STOCK.ANAME AND "
                + "STOCK.SKU = PRODUCTO.SKU ORDER BY PRODUCTO.SKU";
        ResultSet counter = stm.executeQuery(sql);
        int count = 0;
        while(counter.next()){count++;}
        
        String list[][] = new String[count][4];
        int i = 0;
        ResultSet re = stm.executeQuery(sql);
        while(re.next()){
            list[i][0] = re.getString("SKU");
            list[i][1] = re.getString("NOMBRE");
            list[i][2] = re.getNString("ANAME");
            list[i][3] = re.getString("STOCK");
            i++;
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel( list, new String [] {
            "SKU", "NOMBRE " , "NOMBRE ALMACEN" , "STOCK"
        }));
    }
    public void buscar() throws SQLException{
        try {
            String nombreProd = nom_prod.getText();
            String nombreAlm = nom_almacen.getText();
            if((nombreProd.equals("Ingrese el nombre del producto") && nombreAlm.equals("IIngrese el nombre del almacen")) || 
                    (nombreProd.equals("Ingrese el nombre del producto") && nombreAlm.equals("")) ||
                    (nombreProd.equals("") && nombreAlm.equals("Ingrese el nombre del almacen")) || 
                    (nombreProd.equals(" ") && nombreAlm.equals(" ")) )
            {
                GetReports();
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            //en caso de que contenga alguna sentencia
            else{
                String sql = "SELECT * FROM STOCK , PRODUCTO, ALMACEN "
                        + "WHERE ALMACEN.ANAME = STOCK.ANAME "
                        + "AND STOCK.SKU = PRODUCTO.SKU ";
                if(!(nombreProd.equals("") || nombreProd.equals("Ingrese el nombre del producto") || nombreProd.equals(" "))){
                    sql += " AND UPPER(PRODUCTO.NOMBRE) LIKE '%"+ nombreProd.toUpperCase() + "%'";
                }
                if(!(nombreAlm.equals("") || nombreAlm.equals("Ingrese el nombre del almacen") || nombreAlm.equals(" "))){
                    sql += " AND UPPER(ALMACEN.ANAME) LIKE '%" + nombreAlm.toUpperCase() + "%'";
                }
                sql += " ORDER BY PRODUCTO.SKU";
                
                Statement st = reg.createStatement();
                ResultSet counter = st.executeQuery(sql);
                int count = 0;
                while(counter.next()) count++;
                
                System.out.println(sql);
                
                ResultSet rs = st.executeQuery(sql);
                String list[][] = new String [count] [4];
                int i = 0;
                while(rs.next()){
                    list[i][0] = rs.getString("SKU");
                    list[i][1] = rs.getString("NOMBRE");
                    list[i][2] = rs.getString("ANAME");
                    list[i][3] = rs.getString("STOCK");
                    i++; 
                }
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        list , new String[] {"SKU", "NOMBRE " , "NOMBRE ALMACEN" , "STOCK"}
                ));
            }
            } catch (SQLException ex) {
                Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    private void deleteStock() throws SQLException{
        int row = jTable1.getSelectedRow();
        if(row >= 0){
            Statement st = reg.createStatement();
            String sku = (String) jTable1.getModel().getValueAt(row, 0);
            String aname = (String) jTable1.getModel().getValueAt(row, 2);
            String sql = "DELETE FROM STOCK WHERE SKU = "+sku+" AND ANAME = '"+aname+"'"; 
            st.executeUpdate(sql);
            javax.swing.JOptionPane.showMessageDialog(this, "Se ha borrado con éxito \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una fila \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel aniadirStock;
    private javax.swing.JPanel body;
    private javax.swing.JPanel btn_delete;
    private javax.swing.JPanel button1;
    private javax.swing.JPanel button13;
    private javax.swing.JPanel button14;
    private javax.swing.JPanel button15;
    private javax.swing.JPanel button16;
    private javax.swing.JPanel button17;
    private javax.swing.JPanel button18;
    private javax.swing.JPanel button19;
    private javax.swing.JPanel button20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nom_almacen;
    private javax.swing.JTextField nom_prod;
    // End of variables declaration//GEN-END:variables
}
