/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PI_library;

import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author javier
 */
public class UpAlmac extends javax.swing.JPanel {
    
    Connect conn;
    Connection reg;
    boolean edit;
    
    /**
     * Creates new form UpAlmc
     */
    public UpAlmac() {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        edit = false; 
    }
    
    public UpAlmac(String nombre , String direccion){
        initComponents();
        name.setText(nombre);
        name.setEnabled(false);
        dir.setText(direccion);
        
        conn = new Connect();
        reg = conn.getConnection();
        edit = true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        dir = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(750, 430));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 10, 350));

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subir");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 30));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 260, 50));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Nombre Almacen");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        name.setForeground(new java.awt.Color(102, 102, 102));
        name.setText("Ingrese el nombre");
        name.setBorder(null);
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameMousePressed(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 260, -1));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Direccion ");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        dir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dir.setForeground(new java.awt.Color(102, 102, 102));
        dir.setText("Ingrese la direccion del almacen");
        dir.setBorder(null);
        dir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dirMousePressed(evt);
            }
        });
        dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirActionPerformed(evt);
            }
        });
        add(dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 260, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 260, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        setColor(button);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColor(button);
    }//GEN-LAST:event_buttonMouseExited

    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        try {
            updtAlmac();
        } catch (SQLException ex) {
            Logger.getLogger(UpAlmac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMousePressed

    private void nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMousePressed
        if(name.getText().equals("Ingrese el nombre")){
            name.setText("");
        }
        if(dir.getText().equals("")){
            dir.setText("Ingrese la direccion del almacen");
        }
    }//GEN-LAST:event_nameMousePressed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void dirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dirMousePressed
        if(name.getText().equals("")){
            name.setText("Ingrese el nombre");
        }
        if(dir.getText().equals("Ingrese la direccion del almacen")){
            dir.setText("");
        }
    }//GEN-LAST:event_dirMousePressed

    private void dirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        try {
            updtAlmac();
        } catch (SQLException ex) {
            Logger.getLogger(UpAlmac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MousePressed

    private void updtAlmac() throws SQLException{
        if(edit){
            //solo hay que actualizar 
            if(dir.getText().equals("")){
                javax.swing.JOptionPane.showMessageDialog(this, "No puede dejar el campo vacío \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String nombre = name.getText();
            String direccion = dir.getText();
            String sql = "UPDATE ALMACEN "
                    + "SET DIRECCION = '"+direccion+"' "
                    + " WHERE ANAME = '"+nombre+"'";
            
            Statement st = reg.createStatement();
            st.executeUpdate(sql);
            javax.swing.JOptionPane.showMessageDialog(this, "Se han actualizad los datos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            // hay que insertar
            if(dir.getText().equals("") || name.getText().equals("")){
                javax.swing.JOptionPane.showMessageDialog(this, "No puede dejar los campos vacíos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            Statement st = reg.createStatement();
            String nombre = name.getText();
            String direccion = dir.getText();
            String sql = "INSERT INTO ALMACEN VALUES('"+nombre+"'" + ", '"+direccion+"')";
            st.executeUpdate(sql);
            javax.swing.JOptionPane.showMessageDialog(this, "Se ha insertado el registro \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JPanel button;
    private javax.swing.JTextField dir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
