/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PI_library;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

/**
 *
 * @author javier
 */

public class UpProd extends javax.swing.JPanel {

    /**
     * Creates new form UpProd
     */
    
    Connect conn;
    Connection reg;
    boolean edition; 
    
    public UpProd() throws SQLException {
        conn = new Connect();
        reg = conn.getConnection();
        edition = false; 
        initComponents();
        getBoxes();
    }
    
    public UpProd(String sku , String nombre, String precio , String peso , String marca, String subCat)
    {
        conn = new Connect();
        reg = conn.getConnection();
        initComponents();
        edition = true; 
        lbl_sku.setText(sku);
        lbl_sku.setEnabled(false);
        lbl_name.setText(nombre);
        lbl_precio.setText(precio);
        lbl_peso.setText(peso);
        box_marca.setModel(new DefaultComboBoxModel <> (new String [] {marca} ));
        box_subc.setModel(new DefaultComboBoxModel<> (new String [] {subCat} ));
        box_marca.setEnabled(false);
        box_subc.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Text3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        box_subc = new javax.swing.JComboBox<>();
        box_marca = new javax.swing.JComboBox<>();
        Text7 = new javax.swing.JLabel();
        Text8 = new javax.swing.JLabel();
        btn_subir = new javax.swing.JPanel();
        lbl_subir = new javax.swing.JLabel();
        lbl_precio = new javax.swing.JTextField();
        lbl_sku = new javax.swing.JTextField();
        lbl_name = new javax.swing.JTextField();
        lbl_peso = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(750, 430));
        setMinimumSize(new java.awt.Dimension(750, 430));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title1.setText("Actualizar / añadir Producto");
        add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 240, 10));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("SKU");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 60, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 250, 10));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("SUBCATEGORIA");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 120, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 250, 10));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("PESO");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 250, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("PRECIO ");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 100, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 10, 350));

        box_subc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        box_subc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_subc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(box_subc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 280, -1));

        box_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        box_marca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(box_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 280, -1));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("NOMBRE ");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, -1));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("MARCA ");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 120, -1));

        btn_subir.setBackground(new java.awt.Color(18, 90, 173));
        btn_subir.setForeground(new java.awt.Color(18, 90, 173));
        btn_subir.setToolTipText("");
        btn_subir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_subir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_subirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_subirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_subirMousePressed(evt);
            }
        });
        btn_subir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_subir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_subir.setForeground(new java.awt.Color(255, 255, 255));
        lbl_subir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_subir.setText("Subir");
        lbl_subir.setToolTipText("");
        lbl_subir.setVerifyInputWhenFocusTarget(false);
        lbl_subir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_subirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_subirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_subirMousePressed(evt);
            }
        });
        btn_subir.add(lbl_subir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 90, 40));

        add(btn_subir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 130, 40));

        lbl_precio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_precio.setForeground(new java.awt.Color(102, 102, 102));
        lbl_precio.setText("Agregar Precio");
        lbl_precio.setBorder(null);
        lbl_precio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_precioMousePressed(evt);
            }
        });
        lbl_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_precioActionPerformed(evt);
            }
        });
        add(lbl_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 260, 30));

        lbl_sku.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_sku.setForeground(new java.awt.Color(102, 102, 102));
        lbl_sku.setText("Agregar SKU");
        lbl_sku.setBorder(null);
        lbl_sku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_skuMousePressed(evt);
            }
        });
        lbl_sku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_skuActionPerformed(evt);
            }
        });
        add(lbl_sku, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 260, 30));

        lbl_name.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(102, 102, 102));
        lbl_name.setText("Agregar Nombre");
        lbl_name.setBorder(null);
        lbl_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_nameMousePressed(evt);
            }
        });
        lbl_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_nameActionPerformed(evt);
            }
        });
        add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 260, 30));

        lbl_peso.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_peso.setForeground(new java.awt.Color(102, 102, 102));
        lbl_peso.setText("Agregar Peso");
        lbl_peso.setBorder(null);
        lbl_peso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_pesoMousePressed(evt);
            }
        });
        lbl_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_pesoActionPerformed(evt);
            }
        });
        add(lbl_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 260, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_subirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_subirMouseEntered
        setColor(btn_subir);
    }//GEN-LAST:event_lbl_subirMouseEntered

    private void lbl_subirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_subirMouseExited
        resetColor(btn_subir);
    }//GEN-LAST:event_lbl_subirMouseExited

    private void lbl_subirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_subirMousePressed
        try {
            updtProd();
        } catch (SQLException ex) {
            Logger.getLogger(UpProd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbl_subirMousePressed

    private void btn_subirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subirMouseEntered
        setColor(btn_subir);
    }//GEN-LAST:event_btn_subirMouseEntered

    private void btn_subirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subirMouseExited
        resetColor(btn_subir);
    }//GEN-LAST:event_btn_subirMouseExited

    private void btn_subirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subirMousePressed
        try {
            updtProd();
        } catch (SQLException ex) {
            Logger.getLogger(UpProd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_subirMousePressed

    private void lbl_precioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_precioMousePressed
        if(lbl_sku.getText().equals("")){
            lbl_sku.setText("Agregar SKU");
        }
        
        if(lbl_name.getText().equals("")){
            lbl_name.setText("Agregar Nombre");
        }
        
        if(lbl_peso.getText().equals("")){
            lbl_peso.setText("Agregar Peso");
        }
        
        if(lbl_precio.getText().equals("Agregar Precio")){
            lbl_precio.setText("");
        }
    }//GEN-LAST:event_lbl_precioMousePressed

    private void lbl_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_precioActionPerformed

    private void lbl_skuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_skuMousePressed
        if(lbl_sku.getText().equals("Agregar SKU")){
            lbl_sku.setText("");
        }
        
        if(lbl_name.getText().equals("")){
            lbl_name.setText("Agregar Nombre");
        }
        
        if(lbl_peso.getText().equals("")){
            lbl_peso.setText("Agregar Peso");
        }
        
        if(lbl_precio.getText().equals("")){
            lbl_precio.setText("Agregar Precio");
        }
    }//GEN-LAST:event_lbl_skuMousePressed

    private void lbl_skuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_skuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_skuActionPerformed

    private void lbl_nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nameMousePressed
        if(lbl_sku.getText().equals("")){
            lbl_sku.setText("Agregar SKU");
        }
        
        if(lbl_name.getText().equals("Agregar Nombre")){
            lbl_name.setText("");
        }
        
        if(lbl_peso.getText().equals("")){
            lbl_peso.setText("Agregar Peso");
        }
        
        if(lbl_precio.getText().equals("")){
            lbl_precio.setText("Agregar Precio");
        }
    }//GEN-LAST:event_lbl_nameMousePressed

    private void lbl_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_nameActionPerformed

    private void lbl_pesoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pesoMousePressed
        if(lbl_sku.getText().equals("")){
            lbl_sku.setText("Agregar SKU");
        }
        
        if(lbl_name.getText().equals("")){
            lbl_name.setText("Agregar Nombre");
        }
        
        if(lbl_peso.getText().equals("Agregar Peso")){
            lbl_peso.setText("");
        }
        
        if(lbl_precio.getText().equals("")){
            lbl_precio.setText("Agregar Precio");
        }
    }//GEN-LAST:event_lbl_pesoMousePressed

    private void lbl_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_pesoActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(lbl_sku.getText().equals("")){
            lbl_sku.setText("Agregar SKU");
        }
        
        if(lbl_name.getText().equals("")){
            lbl_name.setText("Agregar Nombre");
        }
        
        if(lbl_peso.getText().equals("")){
            lbl_peso.setText("Agregar Peso");
        }
        
        if(lbl_precio.getText().equals("")){
            lbl_precio.setText("Agregar Precio");
        }
    }//GEN-LAST:event_formMouseClicked

    private void updtProd() throws SQLException{
        try{
            if(edition){
                if(lbl_sku.getText().equals("") || lbl_peso.getText().equals("")
                        || lbl_precio.getText().equals("") || lbl_name.getText().equals("")
                        || box_marca.getSelectedItem().equals("--------MARCA--------") 
                        || box_subc.getSelectedItem().equals("--------SUBCATEGORIA--------"))
                {
                    javax.swing.JOptionPane.showMessageDialog(this, "Algunos campos faltan completar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                
                Statement st = reg.createStatement();
                int sku = Integer.parseInt(lbl_sku.getText());
                float peso = Float.parseFloat(lbl_peso.getText());
                float precio = Float.parseFloat(lbl_precio.getText());
                String name = lbl_name.getText();
                String marca = String.valueOf(box_marca.getSelectedItem());
                String subc = String.valueOf(box_subc.getSelectedItem());
                
                String sql = "UPDATE PRODUCTO SET "
                        + "PESO ="+ peso +" , "
                        + "NOMBRE = '"+name+"' , "
                        + "PRECIO = " + precio +", "
                        + "MNAME = '"+marca+"', "
                        + "SUBC = '"+subc+ "' "
                        + "where SKU = " + sku;
                st.executeUpdate(sql);
                javax.swing.JOptionPane.showMessageDialog(this, "Se ha actualizado con éxito. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                if(lbl_sku.getText().equals("") || lbl_peso.getText().equals("")
                        || lbl_precio.getText().equals("") || lbl_name.getText().equals("")
                        || box_marca.getSelectedItem().equals("--------MARCA--------") 
                        || box_subc.getSelectedItem().equals("--------SUBCATEGORIA--------"))
                {
                    javax.swing.JOptionPane.showMessageDialog(this, "Algunos campos faltan completar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                
                Statement st = reg.createStatement();
                int sku = Integer.parseInt(lbl_sku.getText());
                float peso = Float.parseFloat(lbl_peso.getText());
                float precio = Float.parseFloat(lbl_precio.getText());
                String name = lbl_name.getText();
                String marca = String.valueOf(box_marca.getSelectedItem());
                String subc = String.valueOf(box_subc.getSelectedItem());
                String sql = 
                        "INSERT INTO PRODUCTO VALUES"
                        + "("+ precio + ", "+ sku + ", '"+name+"' , "+peso+", '"+ marca +"' , '"+subc+"')";
                st.executeUpdate(sql);
                javax.swing.JOptionPane.showMessageDialog(this, "SE HA INSERTADO EL PRODUCTO CON EXITO. \n", "COMPLETADO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }   
        }catch (NumberFormatException | SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "HA OCURRIDO UN ERROR. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void getBoxes() throws SQLException{
        Statement st = reg.createStatement();
        
        // box subcategoria
        String sql = "SELECT * FROM SUBCAT";
        ResultSet rs = st.executeQuery(sql);
        DefaultComboBoxModel boxModel = new DefaultComboBoxModel(new String [] {"--------SUBCATEGORIA--------"});
        while(rs.next()){
            boxModel.addElement(rs.getString("SUBC"));
        }
        box_subc.setModel(boxModel);
        
        //box marca
        sql = "SELECT * FROM MARCA";
        rs = st.executeQuery(sql);
        boxModel = new DefaultComboBoxModel(new String [] {"--------MARCA--------"});
        while(rs.next()){
            boxModel.addElement(rs.getString("MNAME"));
        }
        box_marca.setModel(boxModel);
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Title1;
    private javax.swing.JComboBox<String> box_marca;
    private javax.swing.JComboBox<String> box_subc;
    private javax.swing.JPanel btn_subir;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField lbl_name;
    private javax.swing.JTextField lbl_peso;
    private javax.swing.JTextField lbl_precio;
    private javax.swing.JTextField lbl_sku;
    private javax.swing.JLabel lbl_subir;
    // End of variables declaration//GEN-END:variables
}
